### ISSUE TITLE
If direction is set to "right", and you drag from left-most edge, it looks broken

### ISSUE THREAD

**Issue by Yuripetusko** [driftyco/ionic-ion-drawer#2]
http://codepen.io/Yuripetusko/pen/NPryqO

![screen shot 2014-12-19 at 00 37 20](https://cloud.githubusercontent.com/assets/666169/5498457/4bd181aa-8717-11e4-9acb-8481eec3eca4.png)

**Comment by kel-sakal-biyik** [comment]
I have created a pull request for this issue. Check it out: https://github.com/driftyco/ionic-ion-drawer/pull/12

**Comment by Yuripetusko** [comment]
Thanks. Will test right away. I did my own fix, but it was so dirty and hacky that I was embarrased to create a PR :D

**Comment by kel-sakal-biyik** [comment]
You are welcome. I hope it helps. Cheers!
