### ISSUE TITLE
The drawer is close or open when I scroll down or up

### ISSUE THREAD

**Issue by cmarrero01** [driftyco/ionic-ion-drawer#6]
I found a big issue with this implementation of drawer, when the menu is scroller to down or up, is extremely sensitive and when I scroll I can drag to left or right.

**Comment by petarov** [comment]
Yeah, that is a bit irritating. What I did as a workaround to this in the `doDrag` function was to prevent the drag to the right from triggering the drawer animation. This, of course, only when the menu is already opened.

This has minimized the sensitivity issue a lot.

**Comment by vitalyrotari** [comment]
You can check my fork version, there is many fixes and improvements. I understand, in this repo is just a small demo without updates.
